platform :ios, '9.0'
use_frameworks!

target 'test' do
  use_frameworks!

  # Pods for test

  target 'testTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testUITests' do
    # Pods for testing
  end

end
